# -*- mode: ruby -*-
# vi: set ft=ruby :

NAME_MASTER="k8s-master"
NAME_NODE_1="k8s-node-1"
NAME_NODE_2="k8s-node-2"

$network = ENV["NETWORK"] || "flannel"

$ip_master = "192.168.33.110"
$ip_node_1 = "192.168.33.120"
$ip_node_2 = "192.168.33.130"

$provision_common = <<SCRIPT
yum -y install git
git clone https://github.com/vlasenkoyuriy/k8s_vagrant.git
SCRIPT

$provision_master = <<SCRIPT
cd k8s_vagrant
./install
./init $(ip a | grep "#{$ip_master}" | grep -o \"[^ ]\\+$\")
KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply -f network/"#{$network}".yml
rm -rf ~/.kube
SCRIPT

$provision_node = <<SCRIPT
cd k8s_vagrant
./install
./join $(ip a | grep "#{$ip_node}" | grep -o \"[^ ]\\+$\") #{$ip_master}:6443
echo 'Done! Joined.'
SCRIPT

$provision_message = <<SCRIPT
echo 'Done! Please run'
echo "vagrant ssh #{NAME_MASTER} -c 'cat /home/vagrant/.kube/config' > ~/.kube/config"
echo 'to get config file of your cluster, or use "vagrant ssh" and kubectl'
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define NAME_MASTER do |master|
    master.vm.hostname = NAME_MASTER
    master.vm.network "private_network", ip: $ip_master

    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = NAME_MASTER
      vb.cpus = 2
    end

    master.vm.provision "shell", inline: $provision_master
  end

  config.vm.define NAME_NODE_1 do |node|
    node.vm.hostname = NAME_NODE_1
    node.vm.network "private_network", ip: $ip_node_1

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = NAME_NODE_1
      vb.cpus = 2
    end

    node.vm.provision "shell", inline: $provision_node
    node.vm.provision "shell", inline: $provision_message
  end

  config.vm.define NAME_NODE_2 do |node|
    node.vm.hostname = NAME_NODE_2
    node.vm.network "private_network", ip: $ip_node_2

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = NAME_NODE_2
      vb.cpus = 2
    end

    node.vm.provision "shell", inline: $provision_node
    node.vm.provision "shell", inline: $provision_message
  end

  config.vm.provision "shell", inline: $provision_common
end
